name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - uses: actions/checkout@v4

      # 2️⃣ Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # or specific version like 3.13.0

      # 3️⃣ Install dependencies
      - name: Get Flutter packages
        run: flutter pub get

      # 4️⃣ Run Flutter analyze
      - name: Analyze project source
        run: flutter analyze

      # 5️⃣ Run Flutter tests
      - name: Run tests
        run: flutter test
